import React, { useRef } from "react";
import Webs from "../components/webs";
import Graficos from "../components/graficos";
import Proyectos from "../components/proyectos";
import Page from "@/components/page";
import Head from "next/head";
import { Poppins } from "next/font/google";
import { motion, useScroll, useTransform } from "framer-motion";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

const Portfolio = () => {
  const refOpacidad = useRef(null);

  const { scrollYProgress: scrollWebs } = useScroll({
    target: refOpacidad,
    offset: ["start start", "end start"],
  });

  //const opacity = useTransform(scrollYProgress, [0, 1], [0, 1]);
  const scalePort = useTransform(scrollWebs, [0, 1], ["0.95", "1"]);
  //const widthPort = useTransform(scrollYProgress, [0, 1], ["80%", "100%"]);
  const yPort = useTransform(scrollWebs, [0, 1], ["5%", "0%"]);
  return (
    <>
      <Head>
        <title>Portafolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Page>
        <div
          ref={refOpacidad}
          className={`hero-inner relative py-28 xl:py-56 px-5 w-full flex items-end ${poppins.className}`}
        >
          <div className="bg-animation"></div>
          <div className="hero_text-container max-w-[100rem] mx-auto xl:px-4">
            <div className=" text-container_box scroll-reveal-loading">
              <h3 className="text-sm xl:text-xl text-center">Portafolio</h3>
              <h1 className="heading-hero text-center mx-auto">
                <span>
                  Proyectos que fusionan diseño y funcionalidad, llevados a cabo
                  con pasión y precisión
                </span>
              </h1>
            </div>
          </div>
        </div>
        <motion.div
          style={{ scale: scalePort, y: yPort }}
          className="yointro section-home-portfolio mx-auto relative flex flex-col items-center bg-[#282828] pt-[10vh] origin-center h-auto overflow-clip"
        >
          <div className="centered grid_portfolio w-full relative ">
            <div className="titles flex justify-center md:flex-row col-span-4 w-full h-[10vw] items-center relative z-40 pb-[10vh]">
              <div className="yointro_text-container text-white px-5">
                <h3 className="text-sm xl:text-xl opacity-50">Lo que hago</h3>
                <h2 className="heading">Diseño y Desarrollo Web</h2>
              </div>
            </div>

            <Webs />
          </div>{" "}
          {/* centered */}
        </motion.div>{" "}
        {/* section-home-portfolio */}
        <div className="yointro section-home-portfolio relative py-28 xl:py-56 px-5 w-full colorido-inner">
          <div className="centered grid_portfolio max-w-[100rem] mx-auto flex flex-col gap-4 md:gap-16">
            <div className="titles flex flex-col w-full">
              <div className="yointro_text-container">
                <h3 className="text-sm xl:text-xl">Lo que hago</h3>
                <h2 className="heading">Diseño Gráfico</h2>
              </div>
              <motion.div
                initial={{
                  width: "0%",
                }}
                whileInView={{
                  width: "100%",
                }}
                viewport={{ once: false }}
                transition={{
                  delay: 0.4,
                  duration: 0.5,
                  ease: "linear",
                }}
                className="w-full h-[1px] bg-black relative mt-4"
              />
            </div>
            <div className="portfolio-items grid gap-4 md:gap-8 md:grid-cols-2 xl:grid-cols-3 col-span-4">
              <Graficos />
            </div>
          </div>{" "}
          {/* centered */}
        </div>{" "}
        {/* section-home-portfolio */}
        <div className="yointro section-home-portfolio relative py-28 xl:py-56 px-5 w-full colorido-inner">
          <div className="centered grid_portfolio max-w-[100rem] mx-auto flex flex-col gap-4 md:gap-16">
            <div className="titles flex flex-col w-full">
              <div className="yointro_text-container">
                <h3 className="text-sm xl:text-xl">Lo que hago</h3>
                <h2 className="heading">Proyectos</h2>
              </div>
              <motion.div
                initial={{
                  width: "0%",
                }}
                whileInView={{
                  width: "100%",
                }}
                viewport={{ once: false }}
                transition={{
                  delay: 0.4,
                  duration: 0.5,
                  ease: "linear",
                }}
                className="w-full h-[1px] bg-black relative mt-4"
              />
            </div>

            <div className="portfolio-items grid gap-4 md:gap-8 md:grid-cols-2 xl:grid-cols-3 col-span-4">
              <Proyectos />
            </div>
          </div>{" "}
          {/* centered */}
        </div>{" "}
        {/* section-home-portfolio */}
      </Page>
    </>
  );
};

export default Portfolio;
