import React, { useRef } from 'react'
import Webs from '../components/webs'
import Graficos from '../components/graficos'
import Proyectos from '../components/proyectos'
import Head from 'next/head'
import { Poppins } from 'next/font/google'
import { motion, useScroll, useTransform } from 'framer-motion'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  variable: '--font-poppins'
})

const Portfolio = () => {
  const refOpacidad = useRef(null)

  const { scrollYProgress: scrollWebs } = useScroll({
    target: refOpacidad,
    offset: ['start start', 'end start']
  })

  //const opacity = useTransform(scrollYProgress, [0, 1], [0, 1]);
  const scalePort = useTransform(scrollWebs, [0, 1], ['0.95', '1'])
  //const widthPort = useTransform(scrollYProgress, [0, 1], ["80%", "100%"]);
  const yPort = useTransform(scrollWebs, [0, 1], ['5%', '0%'])
  return (
    <>
      <Head>
        <title>Portafolio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div
        ref={refOpacidad}
        className={`hero-inner relative flex w-full items-end px-5 py-28 xl:py-56 ${poppins.className}`}
      >
        <div className='bg-animation'></div>
        <div className='hero_text-container mx-auto max-w-[100rem] xl:px-4'>
          <div className='text-container_box scroll-reveal-loading'>
            <h3 className='text-center text-sm xl:text-xl'>Portafolio</h3>
            <h1 className='heading-hero mx-auto text-center'>
              <span>
                Proyectos que fusionan diseño y funcionalidad, llevados a cabo
                con pasión y precisión
              </span>
            </h1>
          </div>
        </div>
      </div>
      <motion.div
        style={{ scale: scalePort, y: yPort }}
        className='yointro section-home-portfolio relative mx-auto flex h-auto origin-center flex-col items-center overflow-clip bg-[#282828] pt-[10vh]'
      >
        <div className='centered grid_portfolio relative w-full'>
          <div className='titles relative z-40 col-span-4 flex h-[10vw] w-full items-center justify-center pb-[10vh] md:flex-row'>
            <div className='yointro_text-container px-5 text-white'>
              <h3 className='text-sm opacity-50 xl:text-xl'>Lo que hago</h3>
              <h2 className='heading'>Diseño y Desarrollo Web</h2>
            </div>
          </div>

          <Webs />
        </div>{' '}
        {/* centered */}
      </motion.div>{' '}
      {/* section-home-portfolio */}
      <div className='yointro section-home-portfolio colorido-inner relative w-full px-5 py-28 xl:py-56'>
        <div className='centered grid_portfolio mx-auto flex max-w-[100rem] flex-col gap-4 md:gap-16'>
          <div className='titles flex w-full flex-col'>
            <div className='yointro_text-container'>
              <h3 className='text-sm xl:text-xl'>Lo que hago</h3>
              <h2 className='heading'>Diseño Gráfico</h2>
            </div>
            <motion.div
              initial={{
                width: '0%'
              }}
              whileInView={{
                width: '100%'
              }}
              viewport={{ once: false }}
              transition={{
                delay: 0.4,
                duration: 0.5,
                ease: 'linear'
              }}
              className='relative mt-4 h-[1px] w-full bg-black'
            />
          </div>
          <div className='portfolio-items col-span-4 grid gap-4 md:grid-cols-2 md:gap-8 xl:grid-cols-3'>
            <Graficos />
          </div>
        </div>{' '}
        {/* centered */}
      </div>{' '}
      {/* section-home-portfolio */}
      <div className='yointro section-home-portfolio colorido-inner relative w-full px-5 py-28 xl:py-56'>
        <div className='centered grid_portfolio mx-auto flex max-w-[100rem] flex-col gap-4 md:gap-16'>
          <div className='titles flex w-full flex-col'>
            <div className='yointro_text-container'>
              <h3 className='text-sm xl:text-xl'>Lo que hago</h3>
              <h2 className='heading'>Proyectos</h2>
            </div>
            <motion.div
              initial={{
                width: '0%'
              }}
              whileInView={{
                width: '100%'
              }}
              viewport={{ once: false }}
              transition={{
                delay: 0.4,
                duration: 0.5,
                ease: 'linear'
              }}
              className='relative mt-4 h-[1px] w-full bg-black'
            />
          </div>

          <div className='portfolio-items col-span-4 grid gap-4 md:grid-cols-2 md:gap-8 xl:grid-cols-3'>
            <Proyectos />
          </div>
        </div>{' '}
        {/* centered */}
      </div>{' '}
      {/* section-home-portfolio */}
    </>
  )
}

export default Portfolio
